# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/blog-repo',
                'doc_host': 'https://inpap.github.io',
                'git_url': 'https://github.com/inpap/blog-repo',
                'lib_path': 'blog_repo'},
  'syms': {'blog_repo.core': {'blog_repo.core.foo': ('core.html#foo', 'blog_repo/core.py')}}}